### ISSUE TITLE
refactorer

### ISSUE THREAD

**Issue by pellegoeg** [aau-claaudia/transcriber#3]
ingen grund til at lave range(len()) på resultatet.

I python kan man itererer over en liste uden af angive længden

https://github.com/aau-claaudia/transcriber/blob/9ccb1440b26e3c56a90f5e8c7381d232635a8aec/app.py#L152C1-L153C1

**Comment by nikko-andersen** [comment]
Jeg har testet det og det virker umiddelbart ikke, nok fordi det er en List[dict[str, Any]]
Får følgende fejl:
TypeError: 'list' object cannot be interpreted as an integer
Har prøvet 
for i in range(transcribed_result):
og
for i in transcribed_result:
